const usuarios = require('./usuarios/usuarios.service.js');
const categorias = require('./categorias/categorias.service.js');
const vendedores = require('./vendedores/vendedores.service.js');
const productos = require('./productos/productos.service.js');
const medallas = require('./medallas/medallas.service.js');
const productosVariantes = require('./productos-variantes/productos-variantes.service.js');
const clientes = require('./clientes/clientes.service.js');
const direcciones = require('./direcciones/direcciones.service.js');
const dataContacto = require('./data-contacto/data-contacto.service.js');
const pedidos = require('./pedidos/pedidos.service.js');
const productosPedido = require('./productos-pedido/productos-pedido.service.js');
const nodos = require('./nodos/nodos.service.js');
const pedidosColectivos = require('./pedidos-colectivos/pedidos-colectivos.service.js');
const usuario = require('./usuario/usuario.service.js');
const vendedorEstrategia = require('./vendedor-estrategia/vendedor-estrategia.service.js');
const vendedorTagOrganizacion = require('./vendedor-tag-organizacion/vendedor-tag-organizacion.service.js');
const vendedorTagProducto = require('./vendedor-tag-producto/vendedor-tag-producto.service.js');
const vendedorTagCobertura = require('./vendedor-tag-cobertura/vendedor-tag-cobertura.service.js');
const tags = require('./tags/tags.service.js');
const medallasProductores = require('./medallas-productores/medallas-productores.service.js');
const productores = require('./productores/productores.service.js');
const vendedorRetiroZonas = require('./vendedor-retiro-zonas/vendedor-retiro-zonas.service.js');
const vendedorRetiroPuntos = require('./vendedor-retiro-puntos/vendedor-retiro-puntos.service.js');
const imagenes = require('./imagenes/imagenes.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(usuarios);
  app.configure(categorias);
  app.configure(vendedores);
  app.configure(productos);
  app.configure(medallas);
  app.configure(productosVariantes);
  app.configure(clientes);
  app.configure(direcciones);
  app.configure(dataContacto);
  app.configure(pedidos);
  app.configure(productosPedido);
  app.configure(nodos);
  app.configure(pedidosColectivos);
  app.configure(usuario);
  app.configure(vendedorEstrategia);
  app.configure(vendedorTagOrganizacion);
  app.configure(vendedorTagProducto);
  app.configure(vendedorTagCobertura);
  app.configure(tags);
  app.configure(medallasProductores);
  app.configure(productores);
  app.configure(vendedorRetiroZonas);
  app.configure(vendedorRetiroPuntos);
  app.configure(imagenes);
};
